### ISSUE TITLE
Servers won't load the mod.

### ISSUE THREAD

**Issue by TeaStrategist** [LambdAurora/Illuminated#2]
When running a 1.21.4 fabric server, the illuminated mod is ignored by the server, and not loaded. 

It does not throw any errors.

The log of the server startup:

```
[21:58:37] [main/INFO]: Loading Minecraft 1.21.4 with Fabric Loader 0.16.9
[21:58:37] [main/INFO]: Loading 4 mods:
	- fabricloader 0.16.9
	   \-- mixinextras 0.4.1
	- java 21
	- minecraft 1.21.4
[21:58:37] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/C:/Users/user/server/libraries/net/fabricmc/sponge-mixin/0.15.4+mixin.0.8.7/sponge-mixin-0.15.4+mixin.0.8.7.jar Service=Knot/Fabric Env=SERVER
[21:58:38] [main/WARN]: Invalid registry value type detected for PerfOS counters. Should be REG_DWORD. Ignoring: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfOS\Performance\Disable Performance Counters.
[21:58:44] [main/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[21:58:46] [main/INFO]: Loaded 1370 recipes
[21:58:46] [main/INFO]: Loaded 1481 advancements
[21:58:46] [Server thread/INFO]: Starting minecraft server version 1.21.4
[21:58:46] [Server thread/INFO]: Loading properties
[21:58:46] [Server thread/INFO]: Default game type: SURVIVAL
[21:58:46] [Server thread/INFO]: Generating keypair
[21:58:46] [Server console handler/ERROR]: Exception handling console input
java.io.IOException: The handle is invalid
	at java.base/java.io.FileInputStream.readBytes(Native Method) ~[?:?]
	at java.base/java.io.FileInputStream.read(FileInputStream.java:287) ~[?:?]
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:345) ~[?:?]
	at java.base/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420) ~[?:?]
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:399) ~[?:?]
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:350) ~[?:?]
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:393) ~[?:?]
	at java.base/sun.nio.cs.StreamDecoder.lockedRead(StreamDecoder.java:217) ~[?:?]
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:171) ~[?:?]
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:188) ~[?:?]
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:160) ~[?:?]
	at java.base/java.io.BufferedReader.implReadLine(BufferedReader.java:370) ~[?:?]
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:347) ~[?:?]
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:436) ~[?:?]
	at knot/net.minecraft.class_3176$1.run(class_3176.java:102) [server-intermediary.jar:?]
[21:58:46] [Server thread/INFO]: Starting Minecraft server on 0.0.0.0:2234
[21:58:47] [Server thread/INFO]: Using default channel type
[21:58:47] [Server thread/INFO]: Preparing level "world"
[21:58:47] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[21:58:48] [Worker-Main-10/INFO]: Preparing spawn area: 0%
[21:58:48] [Worker-Main-10/INFO]: Preparing spawn area: 0%
[21:58:48] [Worker-Main-10/INFO]: Preparing spawn area: 0%
[21:58:48] [Server thread/INFO]: Time elapsed: 1255 ms
[21:58:48] [Server thread/INFO]: Done (1.665s)! For help, type "help"
```

**Comment by LambdAurora** [comment]
We have spotted this issue a few days ago but haven't got time to release an update.
Hopefully an update will be released next week to fix this issue.

In the meantime you can also force the mod to load by replacing `"environment": "client"` with `"environment": "*"` in the fabric.mod.json inside the JAR of the mod.

**Comment by TeaStrategist** [comment]
Thank you for the help!

**Comment by LambdAurora** [comment]
This is now fixed in Illuminated 1.0.1.

I am so sorry for the delays in fixing this issue.
